// Centralized model metadata for CLEX marketing site, models catalog, docs
// and the IDE playground. AUTO-GENERATED from the live NVIDIA /v1/models
// list as of the build that touched this file. Re-run
//   tools/build-models-data.py /tmp/nvmodels.json > public_assets/models-data.js
// to refresh after NVIDIA adds or deprecates models.

window.CLEX_MODELS = window.CLEX_MODELS || [
  {
    name: "llama-4-maverick-17b-128e-instruct",
    publisher: "Meta",
    use: "Meta Llama 4 Maverick \u2014 multimodal text+image, 128 experts.",
    category: "vision",
    nvidiaId: "meta/llama-4-maverick-17b-128e-instruct",
    credits: 15,
  },
  {
    name: "mistral-large-3-675b-instruct-2512",
    publisher: "Mistral",
    use: "Mistral's flagship 675B dense reasoning model.",
    category: "text",
    nvidiaId: "mistralai/mistral-large-3-675b-instruct-2512",
    credits: 15,
  },
  {
    name: "qwen3-coder-480b-a35b-instruct",
    publisher: "Qwen",
    use: "Qwen 480B-A35B coder \u2014 frontier coding model.",
    category: "code",
    nvidiaId: "qwen/qwen3-coder-480b-a35b-instruct",
    credits: 15,
  },
  {
    name: "deepseek-v4-flash",
    publisher: "DeepSeek",
    use: "DeepSeek V4 Flash \u2014 fast frontier reasoning.",
    category: "text",
    nvidiaId: "deepseek-ai/deepseek-v4-flash",
    credits: 10,
  },
  {
    name: "deepseek-v4-pro",
    publisher: "DeepSeek",
    use: "DeepSeek V4 Pro \u2014 frontier reasoning + coding.",
    category: "text",
    nvidiaId: "deepseek-ai/deepseek-v4-pro",
    credits: 10,
  },
  {
    name: "gemma-4-31b-it",
    publisher: "Google",
    use: "Google Gemma 4 31B \u2014 newest open Gemma flagship.",
    category: "text",
    nvidiaId: "google/gemma-4-31b-it",
    credits: 10,
  },
  {
    name: "minimax-m2.5",
    publisher: "MiniMax",
    use: "MiniMax M2.5 \u2014 flagship reasoning + agentic.",
    category: "text",
    nvidiaId: "minimaxai/minimax-m2.5",
    credits: 10,
  },
  {
    name: "minimax-m2.7",
    publisher: "MiniMax",
    use: "MiniMax M2.7 \u2014 latest flagship.",
    category: "text",
    nvidiaId: "minimaxai/minimax-m2.7",
    credits: 10,
  },
  {
    name: "devstral-2-123b-instruct-2512",
    publisher: "Mistral",
    use: "Mistral Devstral 2 123B \u2014 flagship coding model.",
    category: "code",
    nvidiaId: "mistralai/devstral-2-123b-instruct-2512",
    credits: 10,
  },
  {
    name: "mistral-medium-3.5-128b",
    publisher: "Mistral",
    use: "Mistral Medium 3.5 128B \u2014 flagship dense.",
    category: "text",
    nvidiaId: "mistralai/mistral-medium-3.5-128b",
    credits: 10,
  },
  {
    name: "mistral-small-4-119b-2603",
    publisher: "Mistral",
    use: "Mistral Small 4 119B \u2014 newest medium-class flagship.",
    category: "text",
    nvidiaId: "mistralai/mistral-small-4-119b-2603",
    credits: 10,
  },
  {
    name: "kimi-k2-thinking",
    publisher: "Moonshot",
    use: "Moonshot Kimi K2 Thinking \u2014 chain-of-thought reasoning.",
    category: "reasoning",
    nvidiaId: "moonshotai/kimi-k2-thinking",
    credits: 10,
  },
  {
    name: "kimi-k2.6",
    publisher: "Moonshot",
    use: "Moonshot Kimi K2.6 \u2014 flagship long-context reasoning.",
    category: "text",
    nvidiaId: "moonshotai/kimi-k2.6",
    credits: 10,
  },
  {
    name: "llama-3.1-nemotron-ultra-253b-v1",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron Ultra 253B \u2014 frontier reasoning.",
    category: "reasoning",
    nvidiaId: "nvidia/llama-3.1-nemotron-ultra-253b-v1",
    credits: 10,
  },
  {
    name: "nemotron-3-super-120b-a12b",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron 3 Super 120B-A12B \u2014 flagship MoE.",
    category: "text",
    nvidiaId: "nvidia/nemotron-3-super-120b-a12b",
    credits: 10,
  },
  {
    name: "gpt-oss-120b",
    publisher: "OpenAI",
    use: "OpenAI GPT-OSS 120B \u2014 open-weights flagship.",
    category: "text",
    nvidiaId: "openai/gpt-oss-120b",
    credits: 10,
  },
  {
    name: "qwen3.5-397b-a17b",
    publisher: "Qwen",
    use: "Qwen 3.5 397B-A17B \u2014 frontier MoE.",
    category: "text",
    nvidiaId: "qwen/qwen3.5-397b-a17b",
    credits: 10,
  },
  {
    name: "palmyra-creative-122b",
    publisher: "Writer",
    use: "Writer Palmyra Creative 122B \u2014 long-form creative.",
    category: "text",
    nvidiaId: "writer/palmyra-creative-122b",
    credits: 10,
  },
  {
    name: "palmyra-fin-70b-32k",
    publisher: "Writer",
    use: "Writer Palmyra Fin 70B \u2014 finance-tuned.",
    category: "text",
    nvidiaId: "writer/palmyra-fin-70b-32k",
    credits: 10,
  },
  {
    name: "palmyra-med-70b",
    publisher: "Writer",
    use: "Writer Palmyra Med 70B \u2014 medical-tuned.",
    category: "text",
    nvidiaId: "writer/palmyra-med-70b",
    credits: 10,
  },
  {
    name: "palmyra-med-70b-32k",
    publisher: "Writer",
    use: "Writer Palmyra Med 70B \u2014 medical-tuned.",
    category: "text",
    nvidiaId: "writer/palmyra-med-70b-32k",
    credits: 10,
  },
  {
    name: "glm-5.1",
    publisher: "Z.ai",
    use: "Z.ai GLM 5.1 \u2014 newest flagship.",
    category: "text",
    nvidiaId: "z-ai/glm-5.1",
    credits: 10,
  },
  {
    name: "dracarys-llama-3.1-70b-instruct",
    publisher: "Abacus AI",
    use: "Abacus AI Dracarys 70B \u2014 premium fine-tune.",
    category: "text",
    nvidiaId: "abacusai/dracarys-llama-3.1-70b-instruct",
    credits: 5,
  },
  {
    name: "mistral-large",
    publisher: "Mistral",
    use: "Mistral Large \u2014 premium dense.",
    category: "text",
    nvidiaId: "mistralai/mistral-large",
    credits: 5,
  },
  {
    name: "mistral-large-2-instruct",
    publisher: "Mistral",
    use: "Mistral Large 2 \u2014 premium dense.",
    category: "text",
    nvidiaId: "mistralai/mistral-large-2-instruct",
    credits: 5,
  },
  {
    name: "mixtral-8x22b-instruct-v0.1",
    publisher: "Mistral",
    use: "Mistral Mixtral 8\u00d722B \u2014 premium MoE.",
    category: "text",
    nvidiaId: "mistralai/mixtral-8x22b-instruct-v0.1",
    credits: 5,
  },
  {
    name: "kimi-k2-instruct",
    publisher: "Moonshot",
    use: "Moonshot Kimi K2 Instruct \u2014 premium long-context.",
    category: "text",
    nvidiaId: "moonshotai/kimi-k2-instruct",
    credits: 5,
  },
  {
    name: "gpt-oss-20b",
    publisher: "OpenAI",
    use: "OpenAI GPT-OSS 20B \u2014 open-weights mid-flagship.",
    category: "text",
    nvidiaId: "openai/gpt-oss-20b",
    credits: 5,
  },
  {
    name: "qwen3-next-80b-a3b-instruct",
    publisher: "Qwen",
    use: "Qwen 3 Next 80B-A3B \u2014 premium MoE.",
    category: "text",
    nvidiaId: "qwen/qwen3-next-80b-a3b-instruct",
    credits: 5,
  },
  {
    name: "qwen3-next-80b-a3b-thinking",
    publisher: "Qwen",
    use: "Qwen 3 Next 80B-A3B Thinking \u2014 chain-of-thought.",
    category: "reasoning",
    nvidiaId: "qwen/qwen3-next-80b-a3b-thinking",
    credits: 5,
  },
  {
    name: "qwen3.5-122b-a10b",
    publisher: "Qwen",
    use: "Qwen 3.5 122B-A10B \u2014 premium MoE.",
    category: "text",
    nvidiaId: "qwen/qwen3.5-122b-a10b",
    credits: 5,
  },
  {
    name: "step-3.5-flash",
    publisher: "StepFun",
    use: "StepFun 3.5 Flash \u2014 fast premium reasoning.",
    category: "text",
    nvidiaId: "stepfun-ai/step-3.5-flash",
    credits: 5,
  },
  {
    name: "stockmark-2-100b-instruct",
    publisher: "Stockmark",
    use: "Stockmark 2 100B \u2014 premium Japanese-tuned.",
    category: "text",
    nvidiaId: "stockmark/stockmark-2-100b-instruct",
    credits: 5,
  },
  {
    name: "glm4.7",
    publisher: "Z.ai",
    use: "Z.ai GLM 4.7 \u2014 premium reasoning.",
    category: "text",
    nvidiaId: "z-ai/glm4.7",
    credits: 5,
  },
  {
    name: "glm5",
    publisher: "Z.ai",
    use: "Z.ai GLM 5 \u2014 premium reasoning + agentic.",
    category: "text",
    nvidiaId: "z-ai/glm5",
    credits: 5,
  },
  {
    name: "yi-large",
    publisher: "01.AI",
    use: "01.AI Yi Large \u2014 large Chinese-tuned.",
    category: "text",
    nvidiaId: "01-ai/yi-large",
    credits: 3,
  },
  {
    name: "jamba-1.5-large-instruct",
    publisher: "AI21",
    use: "AI21 Jamba 1.5 Large \u2014 large hybrid SSM/Transformer.",
    category: "text",
    nvidiaId: "ai21labs/jamba-1.5-large-instruct",
    credits: 3,
  },
  {
    name: "dbrx-instruct",
    publisher: "Databricks",
    use: "Databricks DBRX 132B-A36B \u2014 large MoE.",
    category: "text",
    nvidiaId: "databricks/dbrx-instruct",
    credits: 3,
  },
  {
    name: "granite-34b-code-instruct",
    publisher: "IBM",
    use: "IBM Granite 34B Code \u2014 large coding model.",
    category: "code",
    nvidiaId: "ibm/granite-34b-code-instruct",
    credits: 3,
  },
  {
    name: "codellama-70b",
    publisher: "Meta",
    use: "Meta CodeLlama 70B \u2014 large coding model.",
    category: "code",
    nvidiaId: "meta/codellama-70b",
    credits: 3,
  },
  {
    name: "llama-3.1-70b-instruct",
    publisher: "Meta",
    use: "Meta Llama 3.1 70B \u2014 large general-purpose.",
    category: "text",
    nvidiaId: "meta/llama-3.1-70b-instruct",
    credits: 3,
  },
  {
    name: "llama-3.2-90b-vision-instruct",
    publisher: "Meta",
    use: "Meta Llama 3.2 90B Vision \u2014 large multimodal.",
    category: "vision",
    nvidiaId: "meta/llama-3.2-90b-vision-instruct",
    credits: 3,
  },
  {
    name: "llama-3.3-70b-instruct",
    publisher: "Meta",
    use: "Meta Llama 3.3 70B \u2014 large general-purpose.",
    category: "text",
    nvidiaId: "meta/llama-3.3-70b-instruct",
    credits: 3,
  },
  {
    name: "llama2-70b",
    publisher: "Meta",
    use: "Meta Llama 2 70B \u2014 legacy large model.",
    category: "text",
    nvidiaId: "meta/llama2-70b",
    credits: 3,
  },
  {
    name: "ising-calibration-1-35b-a3b",
    publisher: "NVIDIA",
    use: "NVIDIA Ising Calibration 1 35B-A3B.",
    category: "text",
    nvidiaId: "nvidia/ising-calibration-1-35b-a3b",
    credits: 3,
  },
  {
    name: "llama-3.1-nemotron-51b-instruct",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron 51B \u2014 large reasoning.",
    category: "text",
    nvidiaId: "nvidia/llama-3.1-nemotron-51b-instruct",
    credits: 3,
  },
  {
    name: "llama-3.1-nemotron-70b-instruct",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron 70B \u2014 large reasoning.",
    category: "text",
    nvidiaId: "nvidia/llama-3.1-nemotron-70b-instruct",
    credits: 3,
  },
  {
    name: "llama-3.3-nemotron-super-49b-v1",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron Super 49B \u2014 large reasoning.",
    category: "text",
    nvidiaId: "nvidia/llama-3.3-nemotron-super-49b-v1",
    credits: 3,
  },
  {
    name: "llama-3.3-nemotron-super-49b-v1.5",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron Super 49B v1.5 \u2014 large reasoning.",
    category: "text",
    nvidiaId: "nvidia/llama-3.3-nemotron-super-49b-v1.5",
    credits: 3,
  },
  {
    name: "llama3-chatqa-1.5-70b",
    publisher: "NVIDIA",
    use: "NVIDIA ChatQA 1.5 70B \u2014 RAG-tuned.",
    category: "text",
    nvidiaId: "nvidia/llama3-chatqa-1.5-70b",
    credits: 3,
  },
  {
    name: "nemotron-3-nano-30b-a3b",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron 3 Nano 30B-A3B.",
    category: "text",
    nvidiaId: "nvidia/nemotron-3-nano-30b-a3b",
    credits: 3,
  },
  {
    name: "nemotron-3-nano-omni-30b-a3b-reasoning",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron 3 Nano Omni 30B-A3B Reasoning.",
    category: "reasoning",
    nvidiaId: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning",
    credits: 3,
  },
  {
    name: "nemotron-4-340b-instruct",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron 4 340B Instruct.",
    category: "text",
    nvidiaId: "nvidia/nemotron-4-340b-instruct",
    credits: 3,
  },
  {
    name: "nemotron-4-340b-reward",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron 4 340B Reward (eval-only).",
    category: "text",
    nvidiaId: "nvidia/nemotron-4-340b-reward",
    credits: 3,
  },
  {
    name: "nemotron-nano-3-30b-a3b",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron Nano 3 30B-A3B.",
    category: "text",
    nvidiaId: "nvidia/nemotron-nano-3-30b-a3b",
    credits: 3,
  },
  {
    name: "qwen2.5-coder-32b-instruct",
    publisher: "Qwen",
    use: "Qwen 2.5 Coder 32B \u2014 large coding model.",
    category: "code",
    nvidiaId: "qwen/qwen2.5-coder-32b-instruct",
    credits: 3,
  },
  {
    name: "starcoder2-15b",
    publisher: "BigCode",
    use: "BigCode StarCoder2 15B.",
    category: "code",
    nvidiaId: "bigcode/starcoder2-15b",
    credits: 2,
  },
  {
    name: "seed-oss-36b-instruct",
    publisher: "ByteDance",
    use: "ByteDance Seed-OSS 36B.",
    category: "text",
    nvidiaId: "bytedance/seed-oss-36b-instruct",
    credits: 2,
  },
  {
    name: "deepseek-coder-6.7b-instruct",
    publisher: "DeepSeek",
    use: "DeepSeek Coder 6.7B.",
    category: "code",
    nvidiaId: "deepseek-ai/deepseek-coder-6.7b-instruct",
    credits: 2,
  },
  {
    name: "gemma-3-12b-it",
    publisher: "Google",
    use: "Google Gemma 3 12B.",
    category: "text",
    nvidiaId: "google/gemma-3-12b-it",
    credits: 2,
  },
  {
    name: "gemma-3-27b-it",
    publisher: "Google",
    use: "Google Gemma 3 27B.",
    category: "text",
    nvidiaId: "google/gemma-3-27b-it",
    credits: 2,
  },
  {
    name: "gemma-3-4b-it",
    publisher: "Google",
    use: "Google Gemma 3 4B.",
    category: "text",
    nvidiaId: "google/gemma-3-4b-it",
    credits: 2,
  },
  {
    name: "gemma-3n-e2b-it",
    publisher: "Google",
    use: "Google Gemma 3n E2B (efficient).",
    category: "text",
    nvidiaId: "google/gemma-3n-e2b-it",
    credits: 2,
  },
  {
    name: "gemma-3n-e4b-it",
    publisher: "Google",
    use: "Google Gemma 3n E4B (efficient).",
    category: "text",
    nvidiaId: "google/gemma-3n-e4b-it",
    credits: 2,
  },
  {
    name: "granite-3.0-3b-a800m-instruct",
    publisher: "IBM",
    use: "IBM Granite 3.0 3B-A800M.",
    category: "text",
    nvidiaId: "ibm/granite-3.0-3b-a800m-instruct",
    credits: 2,
  },
  {
    name: "granite-3.0-8b-instruct",
    publisher: "IBM",
    use: "IBM Granite 3.0 8B.",
    category: "text",
    nvidiaId: "ibm/granite-3.0-8b-instruct",
    credits: 2,
  },
  {
    name: "granite-8b-code-instruct",
    publisher: "IBM",
    use: "IBM Granite 8B Code.",
    category: "code",
    nvidiaId: "ibm/granite-8b-code-instruct",
    credits: 2,
  },
  {
    name: "llama-3.2-11b-vision-instruct",
    publisher: "Meta",
    use: "Meta Llama 3.2 11B Vision \u2014 multimodal mid.",
    category: "vision",
    nvidiaId: "meta/llama-3.2-11b-vision-instruct",
    credits: 2,
  },
  {
    name: "llama-guard-4-12b",
    publisher: "Meta",
    use: "Meta Llama Guard 4 12B \u2014 safety classifier.",
    category: "safety",
    nvidiaId: "meta/llama-guard-4-12b",
    credits: 2,
  },
  {
    name: "kosmos-2",
    publisher: "Microsoft",
    use: "Microsoft Kosmos 2 \u2014 multimodal.",
    category: "vision",
    nvidiaId: "microsoft/kosmos-2",
    credits: 2,
  },
  {
    name: "phi-3-vision-128k-instruct",
    publisher: "Microsoft",
    use: "Microsoft Phi 3 Vision 128K.",
    category: "vision",
    nvidiaId: "microsoft/phi-3-vision-128k-instruct",
    credits: 2,
  },
  {
    name: "phi-3.5-moe-instruct",
    publisher: "Microsoft",
    use: "Microsoft Phi 3.5 MoE.",
    category: "text",
    nvidiaId: "microsoft/phi-3.5-moe-instruct",
    credits: 2,
  },
  {
    name: "phi-4-mini-instruct",
    publisher: "Microsoft",
    use: "Microsoft Phi 4 Mini.",
    category: "text",
    nvidiaId: "microsoft/phi-4-mini-instruct",
    credits: 2,
  },
  {
    name: "phi-4-multimodal-instruct",
    publisher: "Microsoft",
    use: "Microsoft Phi 4 Multimodal.",
    category: "vision",
    nvidiaId: "microsoft/phi-4-multimodal-instruct",
    credits: 2,
  },
  {
    name: "codestral-22b-instruct-v0.1",
    publisher: "Mistral",
    use: "Mistral Codestral 22B.",
    category: "code",
    nvidiaId: "mistralai/codestral-22b-instruct-v0.1",
    credits: 2,
  },
  {
    name: "magistral-small-2506",
    publisher: "Mistral",
    use: "Mistral Magistral Small 2506.",
    category: "text",
    nvidiaId: "mistralai/magistral-small-2506",
    credits: 2,
  },
  {
    name: "ministral-14b-instruct-2512",
    publisher: "Mistral",
    use: "Mistral Ministral 14B.",
    category: "text",
    nvidiaId: "mistralai/ministral-14b-instruct-2512",
    credits: 2,
  },
  {
    name: "mistral-medium-3-instruct",
    publisher: "Mistral",
    use: "Mistral Medium 3.",
    category: "text",
    nvidiaId: "mistralai/mistral-medium-3-instruct",
    credits: 2,
  },
  {
    name: "mistral-nemotron",
    publisher: "Mistral",
    use: "Mistral Nemotron 12B (NVIDIA collab).",
    category: "text",
    nvidiaId: "mistralai/mistral-nemotron",
    credits: 2,
  },
  {
    name: "llama-3.1-nemotron-nano-vl-8b-v1",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron Nano VL 8B \u2014 multimodal.",
    category: "vision",
    nvidiaId: "nvidia/llama-3.1-nemotron-nano-vl-8b-v1",
    credits: 2,
  },
  {
    name: "nemotron-nano-12b-v2-vl",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron Nano 12B v2 VL \u2014 multimodal.",
    category: "vision",
    nvidiaId: "nvidia/nemotron-nano-12b-v2-vl",
    credits: 2,
  },
  {
    name: "neva-22b",
    publisher: "NVIDIA",
    use: "NVIDIA NeVA 22B \u2014 multimodal.",
    category: "vision",
    nvidiaId: "nvidia/neva-22b",
    credits: 2,
  },
  {
    name: "vila",
    publisher: "NVIDIA",
    use: "NVIDIA VILA \u2014 multimodal.",
    category: "vision",
    nvidiaId: "nvidia/vila",
    credits: 2,
  },
  {
    name: "mistral-nemo-12b-instruct",
    publisher: "NVIDIA + Mistral",
    use: "NVIDIA-Mistral Nemo 12B.",
    category: "text",
    nvidiaId: "nv-mistralai/mistral-nemo-12b-instruct",
    credits: 2,
  },
  {
    name: "sarvam-m",
    publisher: "Sarvam AI",
    use: "Sarvam M \u2014 Indic LLM.",
    category: "text",
    nvidiaId: "sarvamai/sarvam-m",
    credits: 2,
  },
  {
    name: "solar-10.7b-instruct",
    publisher: "Upstage",
    use: "Upstage Solar 10.7B.",
    category: "text",
    nvidiaId: "upstage/solar-10.7b-instruct",
    credits: 2,
  },
  {
    name: "sea-lion-7b-instruct",
    publisher: "AI Singapore",
    use: "AI Singapore Sea-Lion 7B.",
    category: "text",
    nvidiaId: "aisingapore/sea-lion-7b-instruct",
    credits: 1,
  },
  {
    name: "fuyu-8b",
    publisher: "Adept",
    use: "Adept Fuyu 8B \u2014 multimodal.",
    category: "vision",
    nvidiaId: "adept/fuyu-8b",
    credits: 1,
  },
  {
    name: "codegemma-1.1-7b",
    publisher: "Google",
    use: "Google CodeGemma 1.1 7B.",
    category: "code",
    nvidiaId: "google/codegemma-1.1-7b",
    credits: 1,
  },
  {
    name: "codegemma-7b",
    publisher: "Google",
    use: "Google CodeGemma 7B.",
    category: "code",
    nvidiaId: "google/codegemma-7b",
    credits: 1,
  },
  {
    name: "deplot",
    publisher: "Google",
    use: "Google DePlot \u2014 chart understanding.",
    category: "vision",
    nvidiaId: "google/deplot",
    credits: 1,
  },
  {
    name: "gemma-2-2b-it",
    publisher: "Google",
    use: "Google Gemma 2 2B.",
    category: "text",
    nvidiaId: "google/gemma-2-2b-it",
    credits: 1,
  },
  {
    name: "gemma-2b",
    publisher: "Google",
    use: "Google Gemma 2B.",
    category: "text",
    nvidiaId: "google/gemma-2b",
    credits: 1,
  },
  {
    name: "recurrentgemma-2b",
    publisher: "Google",
    use: "Google RecurrentGemma 2B.",
    category: "text",
    nvidiaId: "google/recurrentgemma-2b",
    credits: 1,
  },
  {
    name: "llama-3.1-8b-instruct",
    publisher: "Meta",
    use: "Meta Llama 3.1 8B \u2014 fast small.",
    category: "text",
    nvidiaId: "meta/llama-3.1-8b-instruct",
    credits: 1,
  },
  {
    name: "llama-3.2-1b-instruct",
    publisher: "Meta",
    use: "Meta Llama 3.2 1B \u2014 fast small.",
    category: "text",
    nvidiaId: "meta/llama-3.2-1b-instruct",
    credits: 1,
  },
  {
    name: "llama-3.2-3b-instruct",
    publisher: "Meta",
    use: "Meta Llama 3.2 3B \u2014 fast small.",
    category: "text",
    nvidiaId: "meta/llama-3.2-3b-instruct",
    credits: 1,
  },
  {
    name: "mistral-7b-instruct-v0.3",
    publisher: "Mistral",
    use: "Mistral 7B v0.3.",
    category: "text",
    nvidiaId: "mistralai/mistral-7b-instruct-v0.3",
    credits: 1,
  },
  {
    name: "mixtral-8x22b-v0.1",
    publisher: "Mistral",
    use: "Text model",
    category: "text",
    nvidiaId: "mistralai/mixtral-8x22b-v0.1",
    credits: 1,
  },
  {
    name: "mixtral-8x7b-instruct-v0.1",
    publisher: "Mistral",
    use: "Text model",
    category: "text",
    nvidiaId: "mistralai/mixtral-8x7b-instruct-v0.1",
    credits: 1,
  },
  {
    name: "cosmos-reason2-8b",
    publisher: "NVIDIA",
    use: "NVIDIA Cosmos Reason 2 8B.",
    category: "reasoning",
    nvidiaId: "nvidia/cosmos-reason2-8b",
    credits: 1,
  },
  {
    name: "gliner-pii",
    publisher: "NVIDIA",
    use: "NVIDIA GLiNER PII.",
    category: "safety",
    nvidiaId: "nvidia/gliner-pii",
    credits: 1,
  },
  {
    name: "llama-3.1-nemoguard-8b-content-safety",
    publisher: "NVIDIA",
    use: "NVIDIA NemoGuard 8B Content Safety.",
    category: "safety",
    nvidiaId: "nvidia/llama-3.1-nemoguard-8b-content-safety",
    credits: 1,
  },
  {
    name: "llama-3.1-nemoguard-8b-topic-control",
    publisher: "NVIDIA",
    use: "NVIDIA NemoGuard 8B Topic Control.",
    category: "safety",
    nvidiaId: "nvidia/llama-3.1-nemoguard-8b-topic-control",
    credits: 1,
  },
  {
    name: "llama-3.1-nemotron-nano-8b-v1",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron Nano 8B.",
    category: "text",
    nvidiaId: "nvidia/llama-3.1-nemotron-nano-8b-v1",
    credits: 1,
  },
  {
    name: "llama-3.1-nemotron-safety-guard-8b-v3",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron Safety Guard 8B v3.",
    category: "safety",
    nvidiaId: "nvidia/llama-3.1-nemotron-safety-guard-8b-v3",
    credits: 1,
  },
  {
    name: "mistral-nemo-minitron-8b-8k-instruct",
    publisher: "NVIDIA",
    use: "NVIDIA Mistral-Nemo Minitron 8B 8K.",
    category: "text",
    nvidiaId: "nvidia/mistral-nemo-minitron-8b-8k-instruct",
    credits: 1,
  },
  {
    name: "nemotron-3-content-safety",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron 3 Content Safety.",
    category: "safety",
    nvidiaId: "nvidia/nemotron-3-content-safety",
    credits: 1,
  },
  {
    name: "nemotron-content-safety-reasoning-4b",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron Content Safety Reasoning 4B.",
    category: "safety",
    nvidiaId: "nvidia/nemotron-content-safety-reasoning-4b",
    credits: 1,
  },
  {
    name: "nemotron-mini-4b-instruct",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron Mini 4B.",
    category: "text",
    nvidiaId: "nvidia/nemotron-mini-4b-instruct",
    credits: 1,
  },
  {
    name: "nvidia-nemotron-nano-9b-v2",
    publisher: "NVIDIA",
    use: "NVIDIA Nemotron Nano 9B v2.",
    category: "text",
    nvidiaId: "nvidia/nvidia-nemotron-nano-9b-v2",
    credits: 1,
  },
  {
    name: "riva-translate-4b-instruct",
    publisher: "NVIDIA",
    use: "NVIDIA Riva Translate 4B.",
    category: "text",
    nvidiaId: "nvidia/riva-translate-4b-instruct",
    credits: 1,
  },
  {
    name: "riva-translate-4b-instruct-v1.1",
    publisher: "NVIDIA",
    use: "NVIDIA Riva Translate 4B v1.1.",
    category: "text",
    nvidiaId: "nvidia/riva-translate-4b-instruct-v1.1",
    credits: 1,
  },
  {
    name: "zamba2-7b-instruct",
    publisher: "Zyphra",
    use: "Zyphra Zamba 2 7B.",
    category: "text",
    nvidiaId: "zyphra/zamba2-7b-instruct",
    credits: 1,
  },
];

