// ═══════════════════════════════════════════════════════════════════════════
// Server-side mirror of public_assets/models-data.js, scoped to the fields
// the API needs (id + display metadata). Used by /v1/models and the request
// validator in /api/chat.
//
// Generated from public_assets/models-data.js — keep both in sync. The
// authoritative credit cost lives in lib/credits.ts (MODEL_CREDIT_COST).
// ═══════════════════════════════════════════════════════════════════════════

export interface ClexModel {
  name: string;
  publisher: string;
  use: string;
  category: string;
  nvidiaId: string;
}

export const CLEX_MODELS: ClexModel[] = [
  {
    name: "llama-nemotron-rerank-1b-v2",
    publisher: "NVIDIA",
    use: "Text retrieval / reranking",
    category: "embedding",
    nvidiaId: "nvidia/llama-nemotron-rerank-1b-v2",
  },
  {
    name: "qwen3.5-122b-a10b",
    publisher: "Qwen",
    use: "Chat, coding, reasoning",
    category: "text",
    nvidiaId: "qwen/qwen3.5-122b-a10b",
  },
  {
    name: "qwen3.5-397b-a17b",
    publisher: "Qwen",
    use: "Vision, chat, RAG, agentic",
    category: "text",
    nvidiaId: "qwen/qwen3.5-397b-a17b",
  },
  {
    name: "glm5",
    publisher: "Z.ai",
    use: "Reasoning, agentic",
    category: "text",
    nvidiaId: "zhipuai/glm5",
  },
  {
    name: "minimax-m2.5",
    publisher: "Minimaxai",
    use: "Coding, reasoning, office tasks",
    category: "text",
    nvidiaId: "minimaxai/minimax-m2.5",
  },
  {
    name: "minimax-m2.1",
    publisher: "Minimaxai",
    use: "Coding, app/web dev, agentic",
    category: "text",
    nvidiaId: "minimaxai/minimax-m2.1",
  },
  {
    name: "step-3.5-flash",
    publisher: "Stepfun-ai",
    use: "Reasoning, agentic",
    category: "text",
    nvidiaId: "stepfun-ai/step-3.5-flash",
  },
  {
    name: "kimi-k2.5",
    publisher: "Moonshotai",
    use: "Multimodal, video understanding",
    category: "vision",
    nvidiaId: "moonshotai/kimi-k2.5",
  },
  {
    name: "glm4.7",
    publisher: "Z.ai",
    use: "Agentic coding, tool calling",
    category: "text",
    nvidiaId: "zhipuai/glm4.7",
  },
  {
    name: "deepseek-v3.2",
    publisher: "DeepSeek AI",
    use: "Reasoning, long context",
    category: "text",
    nvidiaId: "deepseek-ai/deepseek-v3.2",
  },
  {
    name: "nemotron-3-nano-30b-a3b",
    publisher: "NVIDIA",
    use: "Coding, reasoning, MoE",
    category: "text",
    nvidiaId: "nvidia/nemotron-3-nano-30b-a3b",
  },
  {
    name: "kimi-k2-thinking",
    publisher: "Moonshotai",
    use: "Reasoning, tool use",
    category: "text",
    nvidiaId: "moonshotai/kimi-k2-thinking",
  },
  {
    name: "ministral-14b-instruct-2512",
    publisher: "Mistral AI",
    use: "Chat, instruction following",
    category: "text",
    nvidiaId: "mistralai/ministral-14b-instruct-2512",
  },
  {
    name: "devstral-2-123b-instruct-2512",
    publisher: "Mistral AI",
    use: "Code, reasoning",
    category: "code",
    nvidiaId: "mistralai/devstral-2-123b-instruct-2512",
  },
  {
    name: "deepseek-v3.1-terminus",
    publisher: "DeepSeek AI",
    use: "Agentic, tool calling",
    category: "text",
    nvidiaId: "deepseek-ai/deepseek-v3.1-terminus",
  },
  {
    name: "deepseek-v3.1",
    publisher: "DeepSeek AI",
    use: "Reasoning, tool use",
    category: "text",
    nvidiaId: "deepseek-ai/deepseek-v3.1",
  },
  {
    name: "stockmark-2-100b-instruct",
    publisher: "Stockmark",
    use: "Japanese enterprise LLM",
    category: "text",
    nvidiaId: "stockmark/stockmark-2-100b-instruct",
  },
  {
    name: "qwen3-next-80b-a3b-instruct",
    publisher: "Qwen",
    use: "Chat, long context",
    category: "text",
    nvidiaId: "qwen/qwen3-next-80b-a3b-instruct",
  },
  {
    name: "kimi-k2-instruct-0905",
    publisher: "Moonshotai",
    use: "Reasoning, long context",
    category: "text",
    nvidiaId: "moonshotai/kimi-k2-instruct-0905",
  },
  {
    name: "bielik-11b-v2.6-instruct",
    publisher: "Speakleash",
    use: "Polish language, text generation",
    category: "text",
    nvidiaId: "speakleash/bielik-11b-v2.6-instruct",
  },
  {
    name: "qwen3-next-80b-a3b-thinking",
    publisher: "Qwen",
    use: "Reasoning, multilingual",
    category: "text",
    nvidiaId: "qwen/qwen3-next-80b-a3b-thinking",
  },
  {
    name: "seed-oss-36b-instruct",
    publisher: "ByteDance",
    use: "Reasoning, agentic",
    category: "text",
    nvidiaId: "bytedance/seed-oss-36b-instruct",
  },
  {
    name: "qwen3-coder-480b-a35b-instruct",
    publisher: "Qwen",
    use: "Agentic coding",
    category: "code",
    nvidiaId: "qwen/qwen3-coder-480b-a35b-instruct",
  },
  {
    name: "nvidia-nemotron-nano-9b-v2",
    publisher: "NVIDIA",
    use: "Reasoning, agentic",
    category: "text",
    nvidiaId: "nvidia/nvidia-nemotron-nano-9b-v2",
  },
  {
    name: "llama-3.3-nemotron-super-49b-v1.5",
    publisher: "NVIDIA",
    use: "Reasoning, chat, tool calling",
    category: "text",
    nvidiaId: "nvidia/llama-3.3-nemotron-super-49b-v1.5",
  },
  {
    name: "teuken-7b-instruct-commercial-v0.4",
    publisher: "Opengpt-x",
    use: "EU multilingual LLM",
    category: "text",
    nvidiaId: "opengpt-x/teuken-7b-instruct-commercial-v0.4",
  },
  {
    name: "sarvam-m",
    publisher: "Sarvamai",
    use: "Indian language, coding, math",
    category: "text",
    nvidiaId: "sarvamai/sarvam-m",
  },
  {
    name: "mistral-small-3.1-24b-instruct-2503",
    publisher: "Mistral AI",
    use: "Multilingual, image understanding",
    category: "text",
    nvidiaId: "mistralai/mistral-small-3.1-24b-instruct-2503",
  },
  {
    name: "mistral-medium-3-instruct",
    publisher: "Mistral AI",
    use: "Enterprise, software dev",
    category: "text",
    nvidiaId: "mistralai/mistral-medium-3-instruct",
  },
  {
    name: "llama-3.1-nemotron-ultra-253b-v1",
    publisher: "NVIDIA",
    use: "Scientific reasoning, coding",
    category: "text",
    nvidiaId: "nvidia/llama-3.1-nemotron-ultra-253b-v1",
  },
  {
    name: "llama-4-maverick-17b-128e-instruct",
    publisher: "Meta",
    use: "Multimodal, multilingual",
    category: "vision",
    nvidiaId: "meta/llama-4-maverick-17b-128e-instruct",
  },
  {
    name: "llama-4-scout-17b-16e-instruct",
    publisher: "Meta",
    use: "Multimodal, multilingual",
    category: "vision",
    nvidiaId: "meta/llama-4-scout-17b-16e-instruct",
  },
  {
    name: "llama-3.3-nemotron-super-49b-v1",
    publisher: "NVIDIA",
    use: "Chat, reasoning",
    category: "text",
    nvidiaId: "nvidia/llama-3.3-nemotron-super-49b-v1",
  },
  {
    name: "llama-3.1-nemotron-nano-8b-v1",
    publisher: "NVIDIA",
    use: "Chat, edge",
    category: "text",
    nvidiaId: "nvidia/llama-3.1-nemotron-nano-8b-v1",
  },
  {
    name: "marin-8b-instruct",
    publisher: "Marin",
    use: "Reasoning, math, science",
    category: "text",
    nvidiaId: "marin/marin-8b-instruct",
  },
  {
    name: "granite-3.3-8b-instruct",
    publisher: "IBM",
    use: "Reasoning, coding",
    category: "text",
    nvidiaId: "ibm/granite-3.3-8b-instruct",
  },
  {
    name: "eurollm-9b-instruct",
    publisher: "Utter-project",
    use: "EU multilingual",
    category: "text",
    nvidiaId: "utter-project/eurollm-9b-instruct",
  },
  {
    name: "gemma-2-9b-cpt-sahabatai-instruct",
    publisher: "Gotocompany",
    use: "Indonesian language",
    category: "text",
    nvidiaId: "gotocompany/gemma-2-9b-cpt-sahabatai-instruct",
  },
  {
    name: "phi-4-mini-flash-reasoning",
    publisher: "Microsoft",
    use: "Edge reasoning",
    category: "text",
    nvidiaId: "microsoft/phi-4-mini-flash-reasoning",
  },
  {
    name: "kimi-k2-instruct",
    publisher: "Moonshotai",
    use: "Coding, reasoning, agentic",
    category: "text",
    nvidiaId: "moonshotai/kimi-k2-instruct",
  },
  {
    name: "magistral-small-2506",
    publisher: "Mistral AI",
    use: "Reasoning, edge",
    category: "text",
    nvidiaId: "mistralai/magistral-small-2506",
  },
  {
    name: "llama-guard-4-12b",
    publisher: "Meta",
    use: "Multimodal safety",
    category: "safety",
    nvidiaId: "meta/llama-guard-4-12b",
  },
  {
    name: "gemma-3n-e4b-it",
    publisher: "Google",
    use: "Text/audio/image, edge",
    category: "vision",
    nvidiaId: "google/gemma-3n-e4b-it",
  },
  {
    name: "gemma-3n-e2b-it",
    publisher: "Google",
    use: "Text/audio/image, edge",
    category: "vision",
    nvidiaId: "google/gemma-3n-e2b-it",
  },
  {
    name: "mistral-nemotron",
    publisher: "Mistral AI",
    use: "Coding, agentic",
    category: "code",
    nvidiaId: "mistralai/mistral-nemotron",
  },
  {
    name: "llama-3.1-nemotron-nano-vl-8b-v1",
    publisher: "NVIDIA",
    use: "Vision-language",
    category: "vision",
    nvidiaId: "nvidia/llama-3.1-nemotron-nano-vl-8b-v1",
  },
  {
    name: "llama-3.1-nemotron-nano-4b-v1.1",
    publisher: "NVIDIA",
    use: "Reasoning, edge agents",
    category: "text",
    nvidiaId: "nvidia/llama-3.1-nemotron-nano-4b-v1.1",
  },
  {
    name: "nemotron-content-safety-reasoning-4b",
    publisher: "NVIDIA",
    use: "Safety / guardrails",
    category: "safety",
    nvidiaId: "nvidia/nemotron-content-safety-reasoning-4b",
  },
  {
    name: "llama-3.1-nemotron-safety-guard-8b-v3",
    publisher: "NVIDIA",
    use: "Content moderation",
    category: "safety",
    nvidiaId: "nvidia/llama-3.1-nemotron-safety-guard-8b-v3",
  },
  {
    name: "deepseek-r1-distill-llama-8b",
    publisher: "DeepSeek AI",
    use: "Reasoning (distilled)",
    category: "text",
    nvidiaId: "deepseek-ai/deepseek-r1-distill-llama-8b",
  },
  {
    name: "deepseek-r1-distill-qwen-32b",
    publisher: "DeepSeek AI",
    use: "Coding/reasoning (distilled)",
    category: "text",
    nvidiaId: "deepseek-ai/deepseek-r1-distill-qwen-32b",
  },
  {
    name: "deepseek-r1-distill-qwen-14b",
    publisher: "DeepSeek AI",
    use: "Coding/reasoning (distilled)",
    category: "text",
    nvidiaId: "deepseek-ai/deepseek-r1-distill-qwen-14b",
  },
  {
    name: "deepseek-r1-distill-qwen-7b",
    publisher: "DeepSeek AI",
    use: "Coding/reasoning (distilled)",
    category: "text",
    nvidiaId: "deepseek-ai/deepseek-r1-distill-qwen-7b",
  },
  {
    name: "phi-4-mini-instruct",
    publisher: "Microsoft",
    use: "Chat, multilingual",
    category: "text",
    nvidiaId: "microsoft/phi-4-mini-instruct",
  },
  {
    name: "mistral-small-24b-instruct",
    publisher: "Mistral AI",
    use: "Code, math, general",
    category: "text",
    nvidiaId: "mistralai/mistral-small-24b-instruct",
  },
  {
    name: "llama-3.1-nemoguard-8b-topic-control",
    publisher: "NVIDIA",
    use: "Guardrails/topic control",
    category: "safety",
    nvidiaId: "nvidia/llama-3.1-nemoguard-8b-topic-control",
  },
  {
    name: "nemoguard-jailbreak-detect",
    publisher: "NVIDIA",
    use: "Jailbreak detection",
    category: "safety",
    nvidiaId: "nvidia/nemoguard-jailbreak-detect",
  },
  {
    name: "llama-3.1-nemoguard-8b-content-safety",
    publisher: "NVIDIA",
    use: "Content safety",
    category: "safety",
    nvidiaId: "nvidia/llama-3.1-nemoguard-8b-content-safety",
  },
  {
    name: "colosseum-355b-instruct-16k",
    publisher: "Igenius",
    use: "Enterprise regulated industries",
    category: "text",
    nvidiaId: "igenius/colosseum-355b-instruct-16k",
  },
  {
    name: "falcon3-7b-instruct",
    publisher: "Tiiuae",
    use: "Reasoning, math",
    category: "text",
    nvidiaId: "tiiuae/falcon3-7b-instruct",
  },
  {
    name: "italia-10b-instruct-16k",
    publisher: "Igenius",
    use: "European multilingual",
    category: "text",
    nvidiaId: "igenius/italia-10b-instruct-16k",
  },
  {
    name: "qwen2.5-7b-instruct",
    publisher: "Qwen",
    use: "Chinese & English LLM",
    category: "text",
    nvidiaId: "qwen/qwen2.5-7b-instruct",
  },
  {
    name: "cosmos-nemotron-34b",
    publisher: "NVIDIA",
    use: "Vision-language",
    category: "vision",
    nvidiaId: "nvidia/cosmos-nemotron-34b",
  },
  {
    name: "llama-3.2-nv-embedqa-1b-v2",
    publisher: "NVIDIA",
    use: "Text embedding / retrieval",
    category: "embedding",
    nvidiaId: "nvidia/llama-3.2-nv-embedqa-1b-v2",
  },
  {
    name: "llama-3.2-nv-rerankqa-1b-v2",
    publisher: "NVIDIA",
    use: "Reranking",
    category: "embedding",
    nvidiaId: "nvidia/llama-3.2-nv-rerankqa-1b-v2",
  },
  {
    name: "llama-3.3-70b-instruct",
    publisher: "Meta",
    use: "Reasoning, math",
    category: "text",
    nvidiaId: "meta/llama-3.3-70b-instruct",
  },
  {
    name: "nemotron-4-mini-hindi-4b-instruct",
    publisher: "NVIDIA",
    use: "Hindi-English bilingual",
    category: "text",
    nvidiaId: "nvidia/nemotron-4-mini-hindi-4b-instruct",
  },
  {
    name: "granite-guardian-3.0-8b",
    publisher: "IBM",
    use: "Guardrail",
    category: "safety",
    nvidiaId: "ibm/granite-guardian-3.0-8b",
  },
  {
    name: "llama-3.1-swallow-70b-instruct-v0.1",
    publisher: "Tokyo Institute of Science",
    use: "Japanese sovereign AI",
    category: "text",
    nvidiaId: "tokyotech-llm/llama-3.1-swallow-70b-instruct-v0.1",
  },
  {
    name: "llama-3.1-swallow-8b-instruct-v0.1",
    publisher: "Tokyo Institute of Science",
    use: "Japanese sovereign AI",
    category: "text",
    nvidiaId: "tokyotech-llm/llama-3.1-swallow-8b-instruct-v0.1",
  },
  {
    name: "llama-3.1-nemotron-70b-reward",
    publisher: "NVIDIA",
    use: "Reward model (RLHF)",
    category: "text",
    nvidiaId: "nvidia/llama-3.1-nemotron-70b-reward",
  },
  {
    name: "llama-3.2-3b-instruct",
    publisher: "Meta",
    use: "Chat, reasoning",
    category: "text",
    nvidiaId: "meta/llama-3.2-3b-instruct",
  },
  {
    name: "llama-3.2-1b-instruct",
    publisher: "Meta",
    use: "Chat, reasoning",
    category: "text",
    nvidiaId: "meta/llama-3.2-1b-instruct",
  },
  {
    name: "qwen2-7b-instruct",
    publisher: "Qwen",
    use: "Chinese & English LLM",
    category: "text",
    nvidiaId: "qwen/qwen2-7b-instruct",
  },
  {
    name: "dracarys-llama-3.1-70b-instruct",
    publisher: "Abacus.AI",
    use: "Code, summarization",
    category: "text",
    nvidiaId: "abacusai/dracarys-llama-3.1-70b-instruct",
  },
  {
    name: "llama-3.1-405b-instruct",
    publisher: "Meta",
    use: "Synthetic data, coding",
    category: "text",
    nvidiaId: "meta/llama-3.1-405b-instruct",
  },
  {
    name: "llama-3.1-70b-instruct",
    publisher: "Meta",
    use: "Chat",
    category: "text",
    nvidiaId: "meta/llama-3.1-70b-instruct",
  },
  {
    name: "llama-3.1-8b-instruct",
    publisher: "Meta",
    use: "Chat",
    category: "text",
    nvidiaId: "meta/llama-3.1-8b-instruct",
  },
  {
    name: "phi-3-medium-128k-instruct",
    publisher: "Microsoft",
    use: "Chat, reasoning",
    category: "text",
    nvidiaId: "microsoft/phi-3-medium-128k-instruct",
  },
  {
    name: "gemma-2-27b-it",
    publisher: "Google",
    use: "Chat, text generation",
    category: "text",
    nvidiaId: "google/gemma-2-27b-it",
  },
  {
    name: "gemma-2-9b-it",
    publisher: "Google",
    use: "Chat, text generation",
    category: "text",
    nvidiaId: "google/gemma-2-9b-it",
  },
  {
    name: "llama3-chatqa-1.5-8b",
    publisher: "NVIDIA",
    use: "Text chatbot/search",
    category: "text",
    nvidiaId: "nvidia/llama3-chatqa-1.5-8b",
  },
  {
    name: "mistral-7b-instruct-v0.3",
    publisher: "Mistral AI",
    use: "Chat",
    category: "text",
    nvidiaId: "mistralai/mistral-7b-instruct-v0.3",
  },
  {
    name: "solar-10.7b-instruct",
    publisher: "Upstage",
    use: "NLP, reasoning, math",
    category: "text",
    nvidiaId: "upstage/solar-10.7b-instruct",
  },
  {
    name: "nv-embed-v1",
    publisher: "NVIDIA",
    use: "Text embeddings",
    category: "embedding",
    nvidiaId: "nvidia/nv-embed-v1",
  },
  {
    name: "bge-m3",
    publisher: "BAAI",
    use: "Text retrieval / embeddings",
    category: "embedding",
    nvidiaId: "baai/bge-m3",
  },
  {
    name: "breeze-7b-instruct",
    publisher: "MediaTek",
    use: "Traditional Chinese chat",
    category: "text",
    nvidiaId: "mediatek/breeze-7b-instruct",
  },
  {
    name: "phi-3-small-8k-instruct",
    publisher: "Microsoft",
    use: "Chat",
    category: "text",
    nvidiaId: "microsoft/phi-3-small-8k-instruct",
  },
  {
    name: "phi-3-small-128k-instruct",
    publisher: "Microsoft",
    use: "Chat (long context)",
    category: "text",
    nvidiaId: "microsoft/phi-3-small-128k-instruct",
  },
  {
    name: "phi-3-medium-4k-instruct",
    publisher: "Microsoft",
    use: "Chat",
    category: "text",
    nvidiaId: "microsoft/phi-3-medium-4k-instruct",
  },
  {
    name: "sea-lion-7b-instruct",
    publisher: "AI Singapore",
    use: "Southeast Asian languages",
    category: "text",
    nvidiaId: "ai-singapore/sea-lion-7b-instruct",
  },
  {
    name: "phi-3-mini-4k-instruct",
    publisher: "Microsoft",
    use: "Chat",
    category: "text",
    nvidiaId: "microsoft/phi-3-mini-4k-instruct",
  },
  {
    name: "phi-3-mini-128k-instruct",
    publisher: "Microsoft",
    use: "Chat (long context)",
    category: "text",
    nvidiaId: "microsoft/phi-3-mini-128k-instruct",
  },
  {
    name: "mixtral-8x22b-instruct-v0.1",
    publisher: "Mistral AI",
    use: "Advanced reasoning",
    category: "text",
    nvidiaId: "mistralai/mixtral-8x22b-instruct-v0.1",
  },
  {
    name: "llama3-70b-instruct",
    publisher: "Meta",
    use: "Chat",
    category: "text",
    nvidiaId: "meta/llama3-70b-instruct",
  },
  {
    name: "llama3-8b-instruct",
    publisher: "Meta",
    use: "Chat",
    category: "text",
    nvidiaId: "meta/llama3-8b-instruct",
  },
  {
    name: "rerank-qa-mistral-4b",
    publisher: "NVIDIA",
    use: "Ranking / reranking",
    category: "embedding",
    nvidiaId: "nvidia/rerank-qa-mistral-4b",
  },
  {
    name: "gemma-7b",
    publisher: "Google",
    use: "Chat, text generation",
    category: "text",
    nvidiaId: "google/gemma-7b",
  },
  {
    name: "mistral-7b-instruct-v0.2",
    publisher: "Mistral AI",
    use: "Chat",
    category: "text",
    nvidiaId: "mistralai/mistral-7b-instruct-v0.2",
  },
  {
    name: "mixtral-8x7b-instruct",
    publisher: "Mistral AI",
    use: "Advanced reasoning",
    category: "text",
    nvidiaId: "mistralai/mixtral-8x7b-instruct",
  },
  {
    name: "llama-3-taiwan-70b-instruct",
    publisher: "Yen-Ting Lin",
    use: "Traditional Mandarin",
    category: "text",
    nvidiaId: "yentinglin/llama-3-taiwan-70b-instruct",
  },
  {
    name: "llama-3-swallow-70b-instruct-v0.1",
    publisher: "TokyoTech-LLM",
    use: "Japanese",
    category: "text",
    nvidiaId: "tokyotech-llm/llama-3-swallow-70b-instruct-v0.1",
  },
  {
    name: "jamba-1.5-mini-instruct",
    publisher: "AI21 Labs",
    use: "Chat, generative AI",
    category: "text",
    nvidiaId: "ai21labs/jamba-1.5-mini-instruct",
  },
  {
    name: "nemotron-mini-4b-instruct",
    publisher: "NVIDIA",
    use: "Chat, RAG",
    category: "text",
    nvidiaId: "nvidia/nemotron-mini-4b-instruct",
  },
  {
    name: "mistral-nemo-minitron-8b-base",
    publisher: "NVIDIA",
    use: "Chat, content generation",
    category: "text",
    nvidiaId: "nvidia/mistral-nemo-minitron-8b-base",
  },
  {
    name: "phi-3.5-mini-instruct",
    publisher: "Microsoft",
    use: "Chat, edge",
    category: "text",
    nvidiaId: "microsoft/phi-3.5-mini-instruct",
  },
  {
    name: "rakutenai-7b-instruct",
    publisher: "Rakuten",
    use: "Chat",
    category: "text",
    nvidiaId: "rakuten/rakutenai-7b-instruct",
  },
  {
    name: "rakutenai-7b-chat",
    publisher: "Rakuten",
    use: "Chat",
    category: "text",
    nvidiaId: "rakuten/rakutenai-7b-chat",
  },
  {
    name: "chatglm3-6b",
    publisher: "THUDM",
    use: "Chinese/English chat, translation",
    category: "text",
    nvidiaId: "thudm/chatglm3-6b",
  },
  {
    name: "baichuan2-13b-chat",
    publisher: "Baichuan AI",
    use: "Chinese/English chat",
    category: "text",
    nvidiaId: "baichuan-ai/baichuan2-13b-chat",
  },
  {
    name: "gpt-oss-20b",
    publisher: "OpenAI",
    use: "Text reasoning, math",
    category: "text",
    nvidiaId: "openai/gpt-oss-20b",
  },
  {
    name: "gpt-oss-120b",
    publisher: "OpenAI",
    use: "Text reasoning (MoE)",
    category: "text",
    nvidiaId: "openai/gpt-oss-120b",
  },
  {
    name: "usdcode",
    publisher: "NVIDIA",
    use: "OpenUSD coding",
    category: "code",
    nvidiaId: "nvidia/usdcode",
  },
  {
    name: "qwen2.5-coder-32b-instruct",
    publisher: "Qwen",
    use: "Code generation, reasoning, fixing",
    category: "code",
    nvidiaId: "qwen/qwen2.5-coder-32b-instruct",
  },
  {
    name: "qwen2.5-coder-7b-instruct",
    publisher: "Qwen",
    use: "Code completion",
    category: "code",
    nvidiaId: "qwen/qwen2.5-coder-7b-instruct",
  },
  {
    name: "mamba-codestral-7b-v0.1",
    publisher: "Mistral AI",
    use: "Code completion",
    category: "code",
    nvidiaId: "mistralai/mamba-codestral-7b-v0.1",
  },
  {
    name: "starcoder2-7b",
    publisher: "BigCode",
    use: "Code completion, Python",
    category: "code",
    nvidiaId: "bigcode/starcoder2-7b",
  },
  {
    name: "qwq-32b",
    publisher: "Qwen",
    use: "Coding, reasoning",
    category: "code",
    nvidiaId: "qwen/qwq-32b",
  },
  {
    name: "parakeet-ctc-0.6b-zh-tw",
    publisher: "NVIDIA",
    use: "Mandarin Taiwanese English ASR",
    category: "speech",
    nvidiaId: "nvidia/parakeet-ctc-0.6b-zh-tw",
  },
  {
    name: "parakeet-ctc-0.6b-zh-cn",
    publisher: "NVIDIA",
    use: "Mandarin English ASR",
    category: "speech",
    nvidiaId: "nvidia/parakeet-ctc-0.6b-zh-cn",
  },
  {
    name: "parakeet-ctc-0.6b-es",
    publisher: "NVIDIA",
    use: "Spanish-English ASR",
    category: "speech",
    nvidiaId: "nvidia/parakeet-ctc-0.6b-es",
  },
  {
    name: "parakeet-ctc-0.6b-vi",
    publisher: "NVIDIA",
    use: "Vietnamese-English ASR",
    category: "speech",
    nvidiaId: "nvidia/parakeet-ctc-0.6b-vi",
  },
  {
    name: "parakeet-tdt-0.6b-v2",
    publisher: "NVIDIA",
    use: "English ASR with timestamps",
    category: "speech",
    nvidiaId: "nvidia/parakeet-tdt-0.6b-v2",
  },
  {
    name: "parakeet-ctc-1.1b-asr",
    publisher: "NVIDIA",
    use: "English ASR",
    category: "speech",
    nvidiaId: "nvidia/parakeet-ctc-1.1b-asr",
  },
  {
    name: "parakeet-ctc-0.6b-asr",
    publisher: "NVIDIA",
    use: "English ASR",
    category: "speech",
    nvidiaId: "nvidia/parakeet-ctc-0.6b-asr",
  },
  {
    name: "parakeet-1.1b-rnnt-multilingual-asr",
    publisher: "NVIDIA",
    use: "25-language ASR",
    category: "speech",
    nvidiaId: "nvidia/parakeet-1.1b-rnnt-multilingual-asr",
  },
  {
    name: "whisper-large-v3",
    publisher: "OpenAI",
    use: "Speech recognition",
    category: "speech",
    nvidiaId: "openai/whisper-large-v3",
  },
  {
    name: "canary-1b-asr",
    publisher: "NVIDIA",
    use: "Multilingual speech-to-text & translation",
    category: "speech",
    nvidiaId: "nvidia/canary-1b-asr",
  },
  {
    name: "phi-4-multimodal-instruct",
    publisher: "Microsoft",
    use: "Speech + image reasoning",
    category: "speech",
    nvidiaId: "microsoft/phi-4-multimodal-instruct",
  },
  {
    name: "magpie-tts-flow",
    publisher: "NVIDIA",
    use: "Text-to-speech",
    category: "speech",
    nvidiaId: "nvidia/magpie-tts-flow",
  },
];
